name: Bug Report
description: Report a bug or unexpected behavior in Fluxion
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please fill out the sections below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to trigger the issue.
      placeholder: |
        1. Run `fluxion fetch ...`
        2. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: doctor
    attributes:
      label: Environment
      description: Paste the output of `fluxion doctor --json`
      render: json
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output
      description: Paste any error messages or tracebacks (use `--trace` flag).
      render: text

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - WSL
        - BSD
        - Other
    validations:
      required: true
